# Challenge 3

In this challenge we will work on the `Orders.csv` data set in the previous [Subsetting and Descriptive Stats lab](../../lab-subsetting-and-descriptive-stats/your-code/main.ipynb). In your work you will apply the thinking process and workflow we showed you in Challenge 2.

You are serving as a Business Intelligence Analyst at the headquarter of an international fashion goods chain store. Your boss today asked you to do two things for her:

**First, identify two groups of customers from the data set.** The first group is **VIP Customers** whose **aggregated expenses** at your global chain stores are **above the 95th percentile** (aka. 0.95 quantile). The second group is **Preferred Customers** whose **aggregated expenses** are **between the 75th and 95th percentile**.

**Second, identify which country has the most of your VIP customers, and which country has the most of your VIP+Preferred Customers combined.**

# Q1: How to identify VIP & Preferred Customers?

We start by importing all the required libraries:

In [57]:
# import required libraries
import numpy as np
import pandas as pd

Next, import `Orders.csv` from the "subsetting" lab folder into a dataframe variable called `orders`. Print the head of `orders` to overview the data:

In [63]:
# enter your code here
orders = pd.read_csv("../../lab-subsetting-and-descriptive-stats/your-code/Orders.csv")
orders.head()
orders.drop('Unnamed: 0', inplace=True, axis=1)

---

"Identify VIP and Preferred Customers" is the non-technical goal of your boss. You need to translate that goal into technical languages that data analysts use:

## How to label customers whose aggregated `amount_spent` is in a given quantile range?

We break down the main problem into several sub problems:

#### Sub Problem 1: How to aggregate the  `amount_spent` for unique customers?

#### Sub Problem 2: How to select customers whose aggregated `amount_spent` is in a given quantile range?

#### Sub Problem 3: How to label selected customers as "VIP" or "Preferred"?

*Note: If you want to break down the main problem in a different way, please feel free to revise the sub problems above.*

Now in the workspace below, tackle each of the sub problems using the iterative problem solving workflow. Insert cells as necessary to write your codes and explain your steps.

In [67]:
orders#.groupby('CustomerID')

,InvoiceNo,StockCode,year,month,day,hour,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,amount_spent
0,536365,85123A,2010,12,3,8,white hanging heart t-light holder,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30
1,536365,71053,2010,12,3,8,white metal lantern,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
2,536365,84406B,2010,12,3,8,cream cupid hearts coat hanger,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00
3,536365,84029G,2010,12,3,8,knitted union flag hot water bottle,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
4,536365,84029E,2010,12,3,8,red woolly hottie white heart.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
5,536365,22752,2010,12,3,8,set 7 babushka nesting boxes,2,2010-12-01 08:26:00,7.65,17850,United Kingdom,15.30
6,536365,21730,2010,12,3,8,glass star frosted t-light holder,6,2010-12-01 08:26:00,4.25,17850,United Kingdom,25.50
7,536366,22633,2010,12,3,8,hand warmer union jack,6,2010-12-01 08:28:00,1.85,17850,United Kingdom,11.10
8,536366,22632,2010,12,3,8,hand warmer red polka dot,6,2010-12-01 08:28:00,1.85,17850,United Kingdom,11.10
9,536367,84879,2010,12,3,8,assorted colour bird ornament,32,2010-12-01 08:34:00,1.69,13047,United Kingdom,54.08
10,536367,22745,2010,12,3,8,poppy's playhouse bedroom,6,2010-12-01 08:34:00,2.10,13047,United Kingdom,12.60
11,536367,22748,2010,12,3,8,poppy's playhouse kitchen,6,2010-12-01 08:34:00,2.10,13047,United Kingdom,12.60
12,536367,22749,2010,12,3,8,feltcraft princess charlotte doll,8,2010-12-01 08:34:00,3.75,13047,United Kingdom,30.00
13,536367,22310,2010,12,3,8,ivory knitted mug cosy,6,2010-12-01 08:34:00,1.65,13047,United Kingdom,9.90
14,536367,84969,2010,12,3,8,box of 6 assorted colour teaspoons,6,2010-12-01 08:34:00,4.25,13047,United Kingdom,25.50
15,536367,22623,2010,12,3,8,box of vintage jigsaw blocks,3,2010-12-01 08:34:00,4.95,13047,United Kingdom,14.85
16,536367,22622,2010,12,3,8,box of vintage alphabet blocks,2,2010-12-01 08:34:00,9.95,13047,United Kingdom,19.90
17,536367,21754,2010,12,3,8,home building block word,3,2010-12-01 08:34:00,5.95,13047,United Kingdom,17.85
18,536367,21755,2010,12,3,8,love building block word,3,2010-12-01 08:34:00,5.95,13047,United Kingdom,17.85
19,536367,21777,2010,12,3,8,recipe box with metal heart,4,2010-12-01 08:34:00,7.95,13047,United Kingdom,31.80
20,536367,48187,2010,12,3,8,doormat new england,4,2010-12-01 08:34:00,7.95,13047,United Kingdom,31.80
21,536368,22960,2010,12,3,8,jam making set with jars,6,2010-12-01 08:34:00,4.25,13047,United Kingdom,25.50
22,536368,22913,2010,12,3,8,red coat rack paris fashion,3,2010-12-01 08:34:00,4.95,13047,United Kingdom,14.85
23,536368,22912,2010,12,3,8,yellow coat rack paris fashion,3,2010-12-01 08:34:00,4.95,13047,United Kingdom,14.85
24,536368,22914,2010,12,3,8,blue coat rack paris fashion,3,2010-12-01 08:34:00,4.95,13047,United Kingdom,14.85
25,536369,21756,2010,12,3,8,bath building block word,3,2010-12-01 08:35:00,5.95,13047,United Kingdom,17.85
26,536370,22728,2010,12,3,8,alarm clock bakelike pink,24,2010-12-01 08:45:00,3.75,12583,France,90.00
27,536370,22727,2010,12,3,8,alarm clock bakelike red,24,2010-12-01 08:45:00,3.75,12583,France,90.00
28,536370,22726,2010,12,3,8,alarm clock bakelike green,12,2010-12-01 08:45:00,3.75,12583,France,45.00
29,536370,21724,2010,12,3,8,panda and bunnies sticker sheet,12,2010-12-01 08:45:00,0.85,12583,France,10.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...
397894,581585,22726,2011,12,5,12,alarm clock bakelike green,8,2011-12-09 12:31:00,3.75,15804,United Kingdom,30.00
397895,581585,22727,2011,12,5,12,alarm clock bakelike red,4,2011-12-09 12:31:00,3.75,15804,United Kingdom,15.00
397896,581585,16016,2011,12,5,12,large chinese style scissor,10,2011-12-09 12:31:00,0.85,15804,United Kingdom,8.50
397897,581585,21916,2011,12,5,12,set 12 retro white chalk sticks,24,2011-12-09 12:31:00,0.42,15804,United Kingdom,10.08
397898,581585,84692,2011,12,5,12,box of 24 cocktail parasols,25,2011-12-09 12:31:00,0.42,15804,United Kingdom,10.50
397899,581585,84946,2011,12,5,12,antique silver t-light glass,12,2011-12-09 12:31:00,1.25,15804,United Kingdom,15.00
397900,581585,21684,2011,12,5,12,small medina stamped metal bowl,12,2011-12-09 12:31:00,0.85,15804,United Kingdom,10.20
397901,581585,22398,2011,12,5,12,magnets pack of 4 swallows,12,2011-12-09 12:31:00,0.39,15804,United Kingdom,4.68
397902,581585,23328,2011,12,5,12,set 6 school milk bottles in crate,4,2011-12-09 12:31:00,3.75,15804,United Kingdom,15.00
397903,581585,23145,2011,12,5,12,zinc t-light holder star large,12,2011-12-09 12:31:00,0.95,15804,United Kingdom,11.40
397904,581585,22466,2011,12,5,12,fairy tale cottage night light,12,2011-12-09 12:31:00,1.95,15804,United Kingdom,23.40
397905,581586,22061,2011,12,5,12,large cake stand hanging strawbery,8,2011-12-09 12:49:00,2.95,13113,United Kingdom,23.60
397906,581586,23275,2011,12,5,12,set of 3 hanging owls ollie beak,24,2011-12-09 12:49:00,1.25,13113,United Kingdom,30.00
397907,581586,21217,2011,12,5,12,red retrospot round cake tins,24,2011-12-09 12:49:00,8.95,13113,United Kingdom,214.80
397908,581586,20685,2011,12,5,12,doormat red retrospot,10,2011-12-09 12:49:00,7.08,13113,United Kingdom,70.80
397909,581587,22631,2011,12,5,12,circus parade lunch box,12,2011-12-09 12:50:00,1.95,12680,France,23.40
397910,581587,22556,2011,12,5,12,plasters in tin circus parade,12,2011-12-09 12:50:00,1.65,12680,France,19.80
397911,581587,22555,2011,12,5,12,plasters in tin strongman,12,2011-12-09 12:50:00,1.65,12680,France,19.80
397912,581587,22728,2011,12,5,12,alarm clock bakelike pink,4,2011-12-09 12:50:00,3.75,12680,France,15.00
397913,581587,22727,2011,12,5,12,alarm clock bakelike red,4,2011-12-09 12:50:00,3.75,12680,France,15.00
397914,581587,22726,2011,12,5,12,alarm clock bakelike green,4,2011-12-09 12:50:00,3.75,12680,France,15.00
397915,581587,22730,2011,12,5,12,alarm clock bakelike ivory,4,2011-12-09 12:50:00,3.75,12680,France,15.00
397916,581587,22367,2011,12,5,12,childrens apron spaceboy design,8,2011-12-09 12:50:00,1.95,12680,France,15.60
397917,581587,22629,2011,12,5,12,spaceboy lunch box,12,2011-12-09 12:50:00,1.95,12680,France,23.40
397918,581587,23256,2011,12,5,12,childrens cutlery spaceboy,4,2011-12-09 12:50:00,4.15,12680,France,16.60
397919,581587,22613,2011,12,5,12,pack of 20 spaceboy napkins,12,2011-12-09 12:50:00,0.85,12680,France,10.20
397920,581587,22899,2011,12,5,12,children's apron dolly girl,6,2011-12-09 12:50:00,2.10,12680,France,12.60
397921,581587,23254,2011,12,5,12,childrens cutlery dolly girl,4,2011-12-09 12:50:00,4.15,12680,France,16.60
397922,581587,23255,2011,12,5,12,childrens cutlery circus parade,4,2011-12-09 12:50:00,4.15,12680,France,16.60
397923,581587,22138,2011,12,5,12,baking set 9 piece retrospot,3,2011-12-09 12:50:00,4.95,12680,France,14.85

In [72]:
def get_set(serie_):
    return set(serie_)

agg_funcs = {'amount_spent':sum, 'InvoiceNo':get_set}

agg_funcs = {'amount_spent':sum}

df = orders.groupby('CustomerID').agg(agg_funcs)

In [7]:
# your code here
#orders_by_customer = orders.groupby('CustomerID')["amount_spent"].sum()
#orders_by_customer

CustomerID
12346    77183.60
12347     4310.00
12348     1797.24
12349     1757.55
12350      334.40
           ...
18280      180.60
18281       80.82
18282      178.05
18283     2094.88
18287     1837.28
Name: amount_spent, Length: 4339, dtype: float64

In [73]:
#df = orders.groupby('CustomerID').sum()
df.head()

            amount_spent
CustomerID
12346           77183.60
12347            4310.00
12348            1797.24
12349            1757.55
12350             334.40

In [74]:
df.describe()

        amount_spent
count    4339.000000
mean     2053.793018
std      8988.248381
min         0.000000
25%       307.245000
50%       674.450000
75%      1661.640000
max    280206.020000

In [75]:
quant_75 = df["amount_spent"].quantile(0.75)

In [76]:
quant_95 = df["amount_spent"].quantile(0.95)
quant_95

5840.181999999983

In [77]:
#df["label"] = df[df["amount_spent"] > quant_95, "VIP", "classique"]

df["label"] = np.where(df["amount_spent"] > quant_95, "VIP", np.where(df["amount_spent"] > quant_75, "Preferred", "Classique"))
df.head()

            amount_spent      label
CustomerID
12346           77183.60        VIP
12347            4310.00  Preferred
12348            1797.24  Preferred
12349            1757.55  Preferred
12350             334.40  Classique

In [32]:
#Preferred = df[(df["amount_spent"] > quant_75) & (df["amount_spent"] < quant_95)]

In [78]:
df.loc[df["label"] == 'VIP'].head()

            amount_spent label
CustomerID
12346           77183.60   VIP
12357            6207.67   VIP
12359            6372.58   VIP
12409           11072.67   VIP
12415          124914.53   VIP

In [79]:
df.loc[df["label"] == 'Preferred'].head()

            amount_spent      label
CustomerID
12347            4310.00  Preferred
12348            1797.24  Preferred
12349            1757.55  Preferred
12352            2506.04  Preferred
12356            2811.43  Preferred

Now we'll leave it to you to solve Q2 & Q3, which you can leverage from your solution for Q1:

# Q2: How to identify which country has the most VIP Customers?

# Q3: How to identify which country has the most VIP+Preferred Customers combined?

Provide your solution for Q2 below:

In [84]:
#orders[['CustomerID', 'InvoiceNo']]
orders.head()

,InvoiceNo,StockCode,year,month,day,hour,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,amount_spent
0,536365,85123A,2010,12,3,8,white hanging heart t-light holder,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30
1,536365,71053,2010,12,3,8,white metal lantern,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
2,536365,84406B,2010,12,3,8,cream cupid hearts coat hanger,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00
3,536365,84029G,2010,12,3,8,knitted union flag hot water bottle,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
4,536365,84029E,2010,12,3,8,red woolly hottie white heart.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34

In [85]:
df.head()

            amount_spent      label
CustomerID
12346           77183.60        VIP
12347            4310.00  Preferred
12348            1797.24  Preferred
12349            1757.55  Preferred
12350             334.40  Classique

In [88]:
#On merge les 2 dataFrame pour avoir le label dans la table orders
orders_with_label = orders.join(df, on='CustomerID', how='left', rsuffix='_df')

orders_with_label

,InvoiceNo,StockCode,year,month,day,hour,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,amount_spent,amount_spent_df,label
0,536365,85123A,2010,12,3,8,white hanging heart t-light holder,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30,5391.21,Preferred
1,536365,71053,2010,12,3,8,white metal lantern,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,5391.21,Preferred
2,536365,84406B,2010,12,3,8,cream cupid hearts coat hanger,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00,5391.21,Preferred
3,536365,84029G,2010,12,3,8,knitted union flag hot water bottle,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,5391.21,Preferred
4,536365,84029E,2010,12,3,8,red woolly hottie white heart.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,5391.21,Preferred
5,536365,22752,2010,12,3,8,set 7 babushka nesting boxes,2,2010-12-01 08:26:00,7.65,17850,United Kingdom,15.30,5391.21,Preferred
6,536365,21730,2010,12,3,8,glass star frosted t-light holder,6,2010-12-01 08:26:00,4.25,17850,United Kingdom,25.50,5391.21,Preferred
7,536366,22633,2010,12,3,8,hand warmer union jack,6,2010-12-01 08:28:00,1.85,17850,United Kingdom,11.10,5391.21,Preferred
8,536366,22632,2010,12,3,8,hand warmer red polka dot,6,2010-12-01 08:28:00,1.85,17850,United Kingdom,11.10,5391.21,Preferred
9,536367,84879,2010,12,3,8,assorted colour bird ornament,32,2010-12-01 08:34:00,1.69,13047,United Kingdom,54.08,3237.54,Preferred
10,536367,22745,2010,12,3,8,poppy's playhouse bedroom,6,2010-12-01 08:34:00,2.10,13047,United Kingdom,12.60,3237.54,Preferred
11,536367,22748,2010,12,3,8,poppy's playhouse kitchen,6,2010-12-01 08:34:00,2.10,13047,United Kingdom,12.60,3237.54,Preferred
12,536367,22749,2010,12,3,8,feltcraft princess charlotte doll,8,2010-12-01 08:34:00,3.75,13047,United Kingdom,30.00,3237.54,Preferred
13,536367,22310,2010,12,3,8,ivory knitted mug cosy,6,2010-12-01 08:34:00,1.65,13047,United Kingdom,9.90,3237.54,Preferred
14,536367,84969,2010,12,3,8,box of 6 assorted colour teaspoons,6,2010-12-01 08:34:00,4.25,13047,United Kingdom,25.50,3237.54,Preferred
15,536367,22623,2010,12,3,8,box of vintage jigsaw blocks,3,2010-12-01 08:34:00,4.95,13047,United Kingdom,14.85,3237.54,Preferred
16,536367,22622,2010,12,3,8,box of vintage alphabet blocks,2,2010-12-01 08:34:00,9.95,13047,United Kingdom,19.90,3237.54,Preferred
17,536367,21754,2010,12,3,8,home building block word,3,2010-12-01 08:34:00,5.95,13047,United Kingdom,17.85,3237.54,Preferred
18,536367,21755,2010,12,3,8,love building block word,3,2010-12-01 08:34:00,5.95,13047,United Kingdom,17.85,3237.54,Preferred
19,536367,21777,2010,12,3,8,recipe box with metal heart,4,2010-12-01 08:34:00,7.95,13047,United Kingdom,31.80,3237.54,Preferred
20,536367,48187,2010,12,3,8,doormat new england,4,2010-12-01 08:34:00,7.95,13047,United Kingdom,31.80,3237.54,Preferred
21,536368,22960,2010,12,3,8,jam making set with jars,6,2010-12-01 08:34:00,4.25,13047,United Kingdom,25.50,3237.54,Preferred
22,536368,22913,2010,12,3,8,red coat rack paris fashion,3,2010-12-01 08:34:00,4.95,13047,United Kingdom,14.85,3237.54,Preferred
23,536368,22912,2010,12,3,8,yellow coat rack paris fashion,3,2010-12-01 08:34:00,4.95,13047,United Kingdom,14.85,3237.54,Preferred
24,536368,22914,2010,12,3,8,blue coat rack paris fashion,3,2010-12-01 08:34:00,4.95,13047,United Kingdom,14.85,3237.54,Preferred
25,536369,21756,2010,12,3,8,bath building block word,3,2010-12-01 08:35:00,5.95,13047,United Kingdom,17.85,3237.54,Preferred
26,536370,22728,2010,12,3,8,alarm clock bakelike pink,24,2010-12-01 08:45:00,3.75,12583,France,90.00,7281.38,VIP
27,536370,22727,2010,12,3,8,alarm clock bakelike red,24,2010-12-01 08:45:00,3.75,12583,France,90.00,7281.38,VIP
28,536370,22726,2010,12,3,8,alarm clock bakelike green,12,2010-12-01 08:45:00,3.75,12583,France,45.00,7281.38,VIP
29,536370,21724,2010,12,3,8,panda and bunnies sticker sheet,12,2010-12-01 08:45:00,0.85,12583,France,10.20,7281.38,VIP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397894,581585,22726,2011,12,5,12,alarm clock bakelike green,8,2011-12-09 12:31:00,3.75,15804,United Kingdom,30.00,4206.39,Preferred
397895,581585,22727,2011,12,5,12,alarm clock bakelike red,4,2011-12-09 12:31:00,3.75,15804,United Kingdom,15.00,4206.39,Preferred
397896,581585,16016,2011,12,5,12,large chinese style scissor,10,2011-12-09 12:31:00,0.85,15804,United Kingdom,8.50,4206.39,Preferred
397897,581585,21916,2011,12,5,12,set 12 retro white chalk sticks,24,2011-12-09 12:31:00,0.42,15804,United Kingdom,10.08,4206.39,Preferred
397898,581585,84692,2011,12,5,12,box of 24 cocktail parasols,25,2011-12-09 12:31:00,0.42,15804,United Kingdom,10.50,4206.39,Preferred
397899,581585,84946,2011,12,5,12,antique silver t-light glass,12,2011-12-09 12:31:00,1.25,15804,United Kingdom,15.00,4206.39,Preferred
397900,581585,21684,2011,12,5,12,small medina stamped metal bowl,12,2011-12-09 12:31:00,0.85,15804,United Kingdom,10.20,4206.39,Preferred
397901,581585,22398,2011,12,5,12,magnets pack of 4 swallows,12,2011-12-09 12:31:00,0.39,15804,United Kingdom,4.68,4206.39,Preferred
397902,581585,23328,2011,12,5,12,set 6 school milk bottles in crate,4,2011-12-09 12:31:00,3.75,15804,United Kingdom,15.00,4206.39,Preferred
397903,581585,23145,2011,12,5,12,zinc t-light holder star large,12,2011-12-09 12:31:00,0.95,15804,United Kingdom,11.40,4206.39,Preferred
397904,581585,22466,2011,12,5,12,fairy tale cottage night light,12,2011-12-09 12:31:00,1.95,15804,United Kingdom,23.40,4206.39,Preferred
397905,581586,22061,2011,12,5,12,large cake stand hanging strawbery,8,2011-12-09 12:49:00,2.95,13113,United Kingdom,23.60,12245.96,VIP
397906,581586,23275,2011,12,5,12,set of 3 hanging owls ollie beak,24,2011-12-09 12:49:00,1.25,13113,United Kingdom,30.00,12245.96,VIP
397907,581586,21217,2011,12,5,12,red retrospot round cake tins,24,2011-12-09 12:49:00,8.95,13113,United Kingdom,214.80,12245.96,VIP
397908,581586,20685,2011,12,5,12,doormat red retrospot,10,2011-12-09 12:49:00,7.08,13113,United Kingdom,70.80,12245.96,VIP
397909,581587,22631,2011,12,5,12,circus parade lunch box,12,2011-12-09 12:50:00,1.95,12680,France,23.40,862.81,Classique
397910,581587,22556,2011,12,5,12,plasters in tin circus parade,12,2011-12-09 12:50:00,1.65,12680,France,19.80,862.81,Classique
397911,581587,22555,2011,12,5,12,plasters in tin strongman,12,2011-12-09 12:50:00,1.65,12680,France,19.80,862.81,Classique
397912,581587,22728,2011,12,5,12,alarm clock bakelike pink,4,2011-12-09 12:50:00,3.75,12680,France,15.00,862.81,Classique
397913,581587,22727,2011,12,5,12,alarm clock bakelike red,4,2011-12-09 12:50:00,3.75,12680,France,15.00,862.81,Classique
397914,581587,22726,2011,12,5,12,alarm clock bakelike green,4,2011-12-09 12:50:00,3.75,12680,France,15.00,862.81,Classique
397915,581587,22730,2011,12,5,12,alarm clock bakelike ivory,4,2011-12-09 12:50:00,3.75,12680,France,15.00,862.81,Classique
397916,581587,22367,2011,12,5,12,childrens apron spaceboy design,8,2011-12-09 12:50:00,1.95,12680,France,15.60,862.81,Classique
397917,581587,22629,2011,12,5,12,spaceboy lunch box,12,2011-12-09 12:50:00,1.95,12680,France,23.40,862.81,Classique
397918,581587,23256,2011,12,5,12,childrens cutlery spaceboy,4,2011-12-09 12:50:00,4.15,12680,France,16.60,862.81,Classique
397919,581587,22613,2011,12,5,12,pack of 20 spaceboy napkins,12,2011-12-09 12:50:00,0.85,12680,France,10.20,862.81,Classique
397920,581587,22899,2011,12,5,12,children's apron dolly girl,6,2011-12-09 12:50:00,2.10,12680,France,12.60,862.81,Classique
397921,581587,23254,2011,12,5,12,childrens cutlery dolly girl,4,2011-12-09 12:50:00,4.15,12680,France,16.60,862.81,Classique
397922,581587,23255,2011,12,5,12,childrens cutlery circus parade,4,2011-12-09 12:50:00,4.15,12680,France,16.60,862.81,Classique
397923,581587,22138,2011,12,5,12,baking set 9 piece retrospot,3,2011-12-09 12:50:00,4.95,12680,France,14.85,862.81,Classique

In [105]:
# On groupby orders par country uniquement sur les users VIP et les count 

orders_with_label[orders_with_label['label'] == 'VIP'].groupby('Country')['label'].count().sort_values(ascending = False)

Country
United Kingdom     84185
EIRE                7077
France              3290
Germany             3127
Netherlands         2080
Australia            898
Portugal             681
Switzerland          594
Spain                511
Norway               420
Channel Islands      364
Finland              294
Cyprus               248
Singapore            222
Japan                205
Sweden               198
Belgium               54
Denmark               36
Name: label, dtype: int64

In [106]:
orders_with_label[orders_with_label['label'] == 'Preferred'].groupby('Country')['label'].count().sort_values(ascending = False)

Country
United Kingdom     137450
Germany              4222
France               3011
Belgium              1503
Spain                1058
Switzerland           776
Norway                608
Italy                 507
Portugal              412
Channel Islands       225
Israel                214
Finland               210
Cyprus                203
Iceland               182
Denmark               181
EIRE                  161
Austria               158
Poland                149
Canada                135
Australia             130
Sweden                 75
Japan                  67
Malta                  67
Lebanon                45
Greece                 32
Name: label, dtype: int64

In [97]:
orders_with_label[(orders_with_label['label'] == 'Preferred')&(orders_with_label['Country'] == 'Belgium')]

,InvoiceNo,StockCode,year,month,day,hour,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,amount_spent,amount_spent_df,label
4909,537026,84375,2010,12,5,16,set of 20 kids cookie cutters,12,2010-12-03 16:35:00,2.10,12395,Belgium,25.20,3018.63,Preferred
4910,537026,21217,2010,12,5,16,red retrospot round cake tins,2,2010-12-03 16:35:00,9.95,12395,Belgium,19.90,3018.63,Preferred
4911,537026,21212,2010,12,5,16,pack of 72 retrospot cake cases,120,2010-12-03 16:35:00,0.42,12395,Belgium,50.40,3018.63,Preferred
4912,537026,21977,2010,12,5,16,pack of 60 pink paisley cake cases,120,2010-12-03 16:35:00,0.42,12395,Belgium,50.40,3018.63,Preferred
4913,537026,22417,2010,12,5,16,pack of 60 spaceboy cake cases,120,2010-12-03 16:35:00,0.42,12395,Belgium,50.40,3018.63,Preferred
4914,537026,21975,2010,12,5,16,pack of 60 dinosaur cake cases,48,2010-12-03 16:35:00,0.55,12395,Belgium,26.40,3018.63,Preferred
4915,537026,21976,2010,12,5,16,pack of 60 mushroom cake cases,48,2010-12-03 16:35:00,0.55,12395,Belgium,26.40,3018.63,Preferred
4916,537026,22551,2010,12,5,16,plasters in tin spaceboy,12,2010-12-03 16:35:00,1.65,12395,Belgium,19.80,3018.63,Preferred
4917,537026,85099B,2010,12,5,16,jumbo bag red retrospot,10,2010-12-03 16:35:00,1.95,12395,Belgium,19.50,3018.63,Preferred
4918,537026,22355,2010,12,5,16,charlotte bag suki design,10,2010-12-03 16:35:00,0.85,12395,Belgium,8.50,3018.63,Preferred
4919,537026,84992,2010,12,5,16,72 sweetheart fairy cake cases,24,2010-12-03 16:35:00,0.55,12395,Belgium,13.20,3018.63,Preferred
4920,537026,POST,2010,12,5,16,postage,2,2010-12-03 16:35:00,18.00,12395,Belgium,36.00,3018.63,Preferred
23354,539391,22801,2010,12,5,11,antique glass pedestal bowl,4,2010-12-17 11:51:00,3.75,12417,Belgium,15.00,3649.10,Preferred
23355,539391,22845,2010,12,5,11,vintage cream cat food container,4,2010-12-17 11:51:00,6.35,12417,Belgium,25.40,3649.10,Preferred
23356,539391,22060,2010,12,5,11,large cake stand hanging hearts,4,2010-12-17 11:51:00,9.95,12417,Belgium,39.80,3649.10,Preferred
23357,539391,22423,2010,12,5,11,regency cakestand 3 tier,4,2010-12-17 11:51:00,12.75,12417,Belgium,51.00,3649.10,Preferred
23358,539391,22619,2010,12,5,11,set of 6 soldier skittles,4,2010-12-17 11:51:00,3.75,12417,Belgium,15.00,3649.10,Preferred
23359,539391,21135,2010,12,5,11,victorian metal postcard spring,16,2010-12-17 11:51:00,1.69,12417,Belgium,27.04,3649.10,Preferred
23360,539391,21717,2010,12,5,11,easter tin bucket,8,2010-12-17 11:51:00,2.55,12417,Belgium,20.40,3649.10,Preferred
23361,539391,22451,2010,12,5,11,silk purse babushka red,6,2010-12-17 11:51:00,3.35,12417,Belgium,20.10,3649.10,Preferred
23362,539391,22770,2010,12,5,11,mirror cornice,2,2010-12-17 11:51:00,14.95,12417,Belgium,29.90,3649.10,Preferred
23363,539391,22666,2010,12,5,11,recipe box pantry yellow design,6,2010-12-17 11:51:00,2.95,12417,Belgium,17.70,3649.10,Preferred
23364,539391,POST,2010,12,5,11,postage,2,2010-12-17 11:51:00,15.00,12417,Belgium,30.00,3649.10,Preferred
23747,539447,22630,2010,12,5,16,dolly girl lunch box,12,2010-12-17 16:00:00,1.95,12395,Belgium,23.40,3018.63,Preferred
23748,539447,21880,2010,12,5,16,red retrospot tape,24,2010-12-17 16:00:00,0.19,12395,Belgium,4.56,3018.63,Preferred
23749,539447,21879,2010,12,5,16,hearts gift tape,24,2010-12-17 16:00:00,0.19,12395,Belgium,4.56,3018.63,Preferred
23750,539447,22390,2010,12,5,16,paperweight childhood memories,12,2010-12-17 16:00:00,0.85,12395,Belgium,10.20,3018.63,Preferred
23751,539447,22504,2010,12,5,16,cabin bag vintage retrospot,3,2010-12-17 16:00:00,12.75,12395,Belgium,38.25,3018.63,Preferred
23752,539447,22740,2010,12,5,16,polkadot pen,48,2010-12-17 16:00:00,0.85,12395,Belgium,40.80,3018.63,Preferred
23753,539447,22754,2010,12,5,16,small red babushka notebook,12,2010-12-17 16:00:00,0.85,12395,Belgium,10.20,3018.63,Preferred
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392253,580979,23199,2011,12,2,15,jumbo bag apples,10,2011-12-06 15:40:00,2.08,12362,Belgium,20.80,5226.23,Preferred
392254,580979,23202,2011,12,2,15,jumbo bag vintage leaf,10,2011-12-06 15:40:00,2.08,12362,Belgium,20.80,5226.23,Preferred
392255,580979,85099B,2011,12,2,15,jumbo bag red retrospot,10,2011-12-06 15:40:00,2.08,12362,Belgium,20.80,5226.23,Preferred
392256,580979,23203,2011,12,2,15,jumbo bag vintage doily,10,2011-12-06 15:40:00,2.08,12362,Belgium,20.80,5226.23,Preferred
392257,580979,22816,2011,12,2,15,card motorbike santa,12,2011-12-06 15:40:00,0.42,12362,Belgium,5.04,5226.23,Preferred
392258,580979,22908,2011,12,2,15,pack of 20 napkins red apples,12,2011-12-06 15:40:00,0.85,12362,Belgium,10.20,5226.23,Preferred
392259,580979,23369,2011,12,2,15,set 36 colour pencils love london,16,2011-12-06 15:40:00,1.25,12362,Belgium,20.00,5226.23,Preferred
392260,580979,21704,2011,12,2,15,bag 250g swirly marbles,12,2011-12-06 15:40:00,0.85,12362,Belgium,10.20,5226.23,Preferred
392261,580979,22549,2011,12,2,15,picture dominoes,12,2011-12-06 15:40:00,1.45,12362,Belgium,17.40,5226.23,Preferred
392262,580979,23569,2011,12,2,15,tradtional alphabet stamp set,4,2011-12-06 15:40:00,4.95,12362,Belgium,19.80,5226.23,Preferred
392263,580979,23598,2011,12,2,15,paper bunting vintage party,6,2011-12-06 15:40:00,2.95,12362,Belgium,17.70,5226.23,Preferred
392264,580979,23264,2011,12,2,15,set of 3 wooden sleigh decorations,12,2011-12-06 15:40:00,1.25,12362,Belgium,15.00,5226.23,Preferred
392265,580979,POST,2011,12,2,15,postage,3,2011-12-06 15:40:00,18.00,12362,Belgium,54.00,5226.23,Preferred
397478,581493,79190B,2011,12,5,10,retro plastic polka tray,15,2011-12-09 10:10:00,0.42,12423,Belgium,6.30,1859.31,Preferred
397479,581493,79190A,2011,12,5,10,retro plastic 70's tray,15,2011-12-09 10:10:00,0.42,12423,Belgium,6.30,1859.31,Preferred
397480,581493,22915,2011,12,5,10,assorted bottle top magnets,12,2011-12-09 10:10:00,0.42,12423,Belgium,5.04,1859.31,Preferred
397481,581493,22151,2011,12,5,10,place setting white heart,24,2011-12-09 10:10:00,0.42,12423,Belgium,10.08,1859.31,Preferred
397482,581493,22632,2011,12,5,10,hand warmer red retrospot,12,2011-12-09 10:10:00,2.10,12423,Belgium,25.20,1859.31,Preferred
397483,581493,22865,2011,12,5,10,hand warmer owl design,12,2011-12-09 10:10:00,2.10,12423,Belgium,25.20,1859.31,Preferred
397484,581493,20718,2011,12,5,10,red retrospot shopper bag,10,2011-12-09 10:10:00,1.25,12423,Belgium,12.50,1859.31,Preferred
397485,581493,79191B,2011,12,5,10,retro plastic polka tray,12,2011-12-09 10:10:00,0.85,12423,Belgium,10.20,1859.31,Preferred
397486,581493,71459,2011,12,5,10,hanging jam jar t-light holders,12,2011-12-09 10:10:00,0.85,12423,Belgium,10.20,1859.31,Preferred
397487,581493,84945,2011,12,5,10,multi colour silver t-light holder,12,2011-12-09 10:10:00,0.85,12423,Belgium,10.20,1859.31,Preferred
397488,581493,22356,2011,12,5,10,charlotte bag pink polkadot,10,2011-12-09 10:10:00,0.85,12423,Belgium,8.50,1859.31,Preferred
397489,581493,20724,2011,12,5,10,red retrospot charlotte bag,10,2011-12-09 10:10:00,0.85,12423,Belgium,8.50,1859.31,Preferred
397490,581493,23204,2011,12,5,10,charlotte bag apples design,10,2011-12-09 10:10:00,0.85,12423,Belgium,8.50,1859.31,Preferred
397491,581493,21108,2011,12,5,10,fairy cake flannel assorted colour,18,2011-12-09 10:10:00,0.79,12423,Belgium,14.22,1859.31,Preferred
397492,581493,22252,2011,12,5,10,birdcage decoration tealight holder,12,2011-12-09 10:10:00,1.25,12423,Belgium,15.00,1859.31,Preferred
397493,581493,22807,2011,12,5,10,set of 6 t-lights toadstools,6,2011-12-09 10:10:00,2.95,12423,Belgium,17.70,1859.31,Preferred
397494,581493,POST,2011,12,5,10,postage,1,2011-12-09 10:10:00,15.00,12423,Belgium,15.00,1859.31,Preferred

In [ ]:
# 1503 results

In [108]:
orders_with_label[(orders_with_label['label'] == 'Preferred') | (orders_with_label['label'] == 'VIP')].groupby('Country')['label'].count().sort_values(ascending = False)

Country
United Kingdom     221635
Germany              7349
EIRE                 7238
France               6301
Netherlands          2080
Spain                1569
Belgium              1557
Switzerland          1370
Portugal             1093
Australia            1028
Norway               1028
Channel Islands       589
Italy                 507
Finland               504
Cyprus                451
Sweden                273
Japan                 272
Singapore             222
Denmark               217
Israel                214
Iceland               182
Austria               158
Poland                149
Canada                135
Malta                  67
Lebanon                45
Greece                 32
Name: label, dtype: int64